name: local_badge-buddy
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - local_server

  processor-1:
    container_name: local_badge-buddy-processor-1
    depends_on:
      - redis
    build:
      context: .
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    networks:
      - local_server
    volumes:
      - ./logs:/app/logs

networks:
  local_server:
    external: true
