export const ENV_AUTH_PROCESSOR_CLIENT_ID = 'AUTH_PROCESSOR_CLIENT_ID' as const;
export const ENV_AUTH_PROCESSOR_CLIENT_SECRET =
  'AUTH_PROCESSOR_CLIENT_SECRET' as const;
export const ENV_BADGE_BUDDY_API_HOST = 'BADGE_BUDDY_API_HOST' as const;
