#file: noinspection YAMLSchemaValidation
name: Create PR for dev
on:
  push:
    branches:
      - dev

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  prepare-versions:
    outputs:
      pnpm: ${{ steps.pnpm-version.outputs.prop }}
      node: ${{ steps.node-version.outputs.prop }}
      package: ${{ steps.package-version.outputs.prop }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve node version
        id: node-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.node'
      - name: Retrieve pnpm version
        id: pnpm-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.pnpm'
      - name: Retrieve package version
        id: package-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
  build-and-test:
    needs: prepare-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.prepare-versions.outputs.node }}
      - run: npm install -g pnpm@${{ needs.prepare-versions.outputs.pnpm }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
  build-deploy-docker:
    needs: build-and-test
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/badge-buddy-processor:dev
            ${{ secrets.DOCKER_USERNAME }}/badge-buddy-processor:${{ needs.prepare-versions.outputs.package }}
          build-args: |
            NODE_VERSION=${{ needs.prepare-versions.outputs.node }}
            PNPM_VERSION=${{ needs.prepare-versions.outputs.pnpm }}
  deploy-qa:
    needs: build-deploy-docker
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY_STAGING }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOTENV_KEY,GH_TOKEN
          script: |
            curl -H "Authorization: token $GH_TOKEN" \
                 -H 'Accept: application/vnd.github.v3.raw' \
                 -o 'compose.yml' \
                 -L 'https://api.github.com/repos/solidchain-tech/badge-buddy-processor/contents/compose.yml?ref=dev'
            docker compose --profile staging pull
            docker compose --profile staging stop
            docker compose --profile staging up --build -d
  create-pr:
    needs: deploy-qa
    environment: development
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: git fetch origin
      - run: gh pr close dev | exit 0
      - run: gh pr create --base release/dev --fill --title "dev -> release/dev" | exit 0
